import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Box, Button, Container, Heading, Icon, Stack, Text } from '@chakra-ui/react'
import {useRouter} from 'next/router'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Container maxW={'3xl'}>
          <Stack
            as={Box}
            textAlign={'center'}
            spacing={{ base: 8, md: 14 }}
            py={{ base: 20, md: 36 }}>
            <Heading
              fontWeight={600}
              fontSize={{ base: '2xl', sm: '4xl', md: '6xl' }}
              lineHeight={'110%'}>
              Unlock Your Learning Potential with  <br />
              <Text color={'purple.400'} fontWeight={'bold'} as='span'>
              StudyHacks
              </Text>
            </Heading>
            <Text color={'gray.500'}>
              Welcome to StudyHacks, your gateway to simplified learning. Discover how our AI-powered platform transforms your notes and materials into personalized study guides, making complex topics easier to master.
            </Text>
            <Stack
              direction={'column'}
              spacing={3}
              align={'center'}
              alignSelf={'center'}
              position={'relative'}>
              <Button
                onClick={(()=>{router.push('/app')})}
                colorScheme={'purple'}
                bg={'purple.400'}
                rounded={'full'}
                px={6}
                _hover={{
                  bg: 'purple.500',
                }}>
                Get Started
              </Button>
              <Button variant={'link'} colorScheme={'blue'} size={'sm'}>
                Learn more
              </Button>
            </Stack>
          </Stack>
        </Container>
      </main>
    </>
  )
}
